apiVersion: v1
data:
  allow-snippet-annotations: "true"
  use-forwarded-headers: 'true'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: nginx
    meta.helm.sh/release-namespace: nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.3.1
    helm.sh/chart: ingress-nginx-4.2.5
  name: nginx-ingress-nginx-controller
  namespace: nginx
  resourceVersion: "22456"
